### ISSUE TITLE
Waarom was kopje "Arrays" weggehaald bij de loops-oefeningen?

### ISSUE THREAD

**Issue by stgm** [minprog/exercises#1]
Deze specifieke oefeningen waren weggehaald bij ProgIK.

https://github.com/minprog/exercises/blob/main/50%20Loops/content.md#arrays

**Comment by stgm** [comment]
@Jelleas Weet jij dat nog?

**Comment by Jelleas** [comment]
De reden hiervoor weet ik niet heel zeker. ,Maar bij ProgIK hebben we mij niet alle toetsjes gedaan. O.a. omdat het tentamen (herhaling van alle toetsjes) al in week 4 was. Ik vermoed dat dit stuk net niet meer in de toetsjes / het tentamen kwam.

**Comment by stgm** [comment]
Prima :-)
